### ISSUE TITLE
Odamex version does not point to 10.4.0

### ISSUE THREAD

**Issue by Edward850** [fopwoc/odamex-docker#2]
Despite what is tagged in the project itself, the package used does not point to 10.4.0. It's still downloading 10.3.0.

**Comment by fopwoc** [comment]
<img width="936" alt="image" src="https://github.com/fopwoc/odamex-docker/assets/21304354/434992c0-0710-4b2b-be17-8a4a3ba80942">
Well, last update broke CI and i forget to fix this... Gotta look today.

**Comment by fopwoc** [comment]
Fixed! Please tell me that it actually works (or not).

**Comment by Edward850** [comment]
I receive the error "no matching manifest for linux/amd64 in the manifest lists entries"

**Comment by fopwoc** [comment]
Well, it was really horrible idea to spend entire week to add arm64 build option while fix of main issue will have taken about 5 minutes or so... But now it's working the way it's supposed to...

Btw arm64 is a bit mess due to ghcr does not work with platforms as i expect.

<img width="1125" alt="image" src="https://github.com/fopwoc/odamex-docker/assets/21304354/d7ecf0ed-99bb-4f30-b571-76b706dd7f56">
